version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: velach_bot
      POSTGRES_USER: velach_bot
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    command: npm start
    volumes:
      - .:/app
    depends_on:
      - db